// frontend/src/components/messages/MessageInput.tsx
import { useRef, useState } from 'react'
import { Paperclip, Send } from 'lucide-react'

interface MessageInputProps {
  disabled?: boolean
  onSend: (text: string) => void | Promise<void>
}

export default function MessageInput({ disabled, onSend }: MessageInputProps) {
  const inputRef = useRef<HTMLInputElement>(null)
  const [value, setValue] = useState('')

  function emitSend() {
    const text = value.trim()
    if (!text || disabled) return
    setValue('')
    void onSend(text)
  }

  return (
    <div className="relative px-6 pb-6">
      <div
        className="flex h-[42px] w-full items-center justify-between rounded-3xl border-2 border-[#77B5FF] bg-white px-4 py-[9px] shadow-[2px_2px_4px_rgba(0,0,0,0.25)]"
        onClick={() => inputRef.current?.focus()}
      >
        <div className="flex flex-1 items-center gap-3">
          <Paperclip className="h-5 w-5 flex-shrink-0 text-[#528DD2]" />
          <input
            ref={inputRef}
            type="text"
            value={value}
            disabled={disabled}
            onChange={e => setValue(e.target.value)}
            onKeyUp={e => {
              if (e.key === 'Enter') emitSend()
            }}
            placeholder="輸入訊息......"
            className="w-full border-0 bg-transparent p-0 font-['Noto_Sans_TC',sans-serif] text-base leading-[140%] text-black/[0.87] outline-none placeholder:text-black/[0.38]"
          />
        </div>
        <button
          type="button"
          onClick={emitSend}
          disabled={disabled}
          className="flex h-6 w-6 flex-shrink-0 items-center justify-center text-[#528DD2] transition disabled:opacity-40"
          aria-label="送出"
        >
          <Send className="h-5 w-5" />
        </button>
      </div>
    </div>
  )
}

// frontend/src/components/MessageInput.vue
<template>
  <div class="messages-container">
    <div class="input-container">
      <div class="textbar" @click="focusInput">
        <div class="content">
          <i class="fas fa-paperclip attach-icon"></i>
          <input
            ref="inputRef"
            v-model="inputValue"
            @keyup.enter="emitSend"
            class="message-input"
            placeholder="輸入訊息......"
            type="text"
          >
        </div>
        <div class="send" @click="emitSend">
          <i class="fas fa-paper-plane send-icon"></i>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, watch } from 'vue'

const props = defineProps({
  modelValue: String
})

const emit = defineEmits(['update:modelValue', 'send'])
const inputValue = ref(props.modelValue || '')
const inputRef = ref(null)

watch(() => props.modelValue, val => { inputValue.value = val })
watch(inputValue, val => emit('update:modelValue', val))

function emitSend() {
  if (!inputValue.value.trim()) return
  emit('send')
}

function focusInput() {
  inputRef.value && inputRef.value.focus()
}
</script>

<style scoped>
.input-container {
  position: absolute;
  left: 24px;
  right: 24px;
  bottom: 0;
  margin-bottom: 24px;
  padding: 0;
}

.textbar {
  width: 100%;
  height: 42px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  border-radius: 24px;
  padding: 9px 16px;
  border: 2px solid #77B5FF;
  box-shadow: 2px 2px 4px 0px #00000040;
  background: #fff;
  box-sizing: border-box;
  cursor: pointer;
}

.content {
  display: flex;
  align-items: center;
  width: 180px;
  height: 24px;
  gap: 12px;
}

.attach-icon {
  width: 11px;
  height: 20px;
  color: #528DD2;
  font-size: 20px;
  margin-right: 6px;
}

.message-input {
  width: 144px;
  height: 22px;
  border: none;
  outline: none;
  font-family: 'Noto Sans TC', sans-serif;
  font-weight: 400;
  font-size: 16px;
  line-height: 140%;
  background: transparent;
  color: #000000DE;
  letter-spacing: 0;
  padding: 0;
}

.message-input::placeholder {
  color: #00000061;
}

.send {
  width: 24px;
  height: 24px;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
}

.send-icon {
  width: 24px;
  height: 24px;
  color: #528DD2;
  font-size: 20px;
  margin-left: 3px;
  margin-top: 4px;
}

.messages-container {
  position: relative;
}
</style>
