// frontend/src/components/orders/OrderTable.tsx
import { useMemo, useState, type ReactNode } from 'react'
import axios from 'axios'
import { exportDocx, deleteOrder } from '@/api/orders'
import type { OrderRecord } from '@/types/models'
import { getStatusDisplay, normalizeOrderStatus, orderStatusBadgeClass } from '@/utils/statusMapping'
import './OrderTable.css'

const columnMapping: Record<string, keyof OrderRecord> = {
  匯出工單: 'order_status',
  訂單編號: 'id',
  狀態: 'order_status',
  取貨時間: 'send_datetime',
  姓名: 'customer_name',
  電話: 'customer_phone',
  商品: 'item',
  數量: 'quantity',
  備註: 'note',
  取貨方式: 'shipment_method',
  金額: 'total_amount',
  付款方式: 'pay_way',
  付款狀態: 'pay_status',
  取消訂單: 'id',
}

const columnWidths: Record<string, string> = {
  訂單編號: '136px',
  狀態: '120px',
  取貨時間: '200px',
  姓名: '96px',
  電話: '112px',
  商品: '96px',
  數量: '96px',
  備註: '128px',
  取貨方式: '128px',
  金額: '96px',
  付款方式: '128px',
  付款狀態: '112px',
  取消訂單: '96px',
}

type StatusTab = 'WELCOME' | 'ORDER_CONFIRM' | 'WAITING_OWNER' | 'BOT_ACTIVE' | ''

function getErrorDetail(err: unknown): string {
  if (axios.isAxiosError(err)) {
    const raw = err.response?.data as { detail?: unknown } | undefined
    if (raw && raw.detail !== undefined) return String(raw.detail)
    return err.message
  }
  if (err instanceof Error) return err.message
  return String(err)
}

interface OrderTableProps {
  /** Raw rows exactly as returned by /orders */
  data: OrderRecord[]
  columnName: string[]
  /** Called after a successful DELETE so parent can invalidate queries or refetch */
  onOrderDeleted?: () => void | Promise<void>
}

export default function OrderTable({ data, columnName, onOrderDeleted }: OrderTableProps) {
  const [searchText, setSearchText] = useState('')
  const [currentDate, setCurrentDate] = useState(() => new Date())
  const [activeTab, setActiveTab] = useState<StatusTab>('')
  const [dateFilterActive, setDateFilterActive] = useState(false)

  const normalizedRows = useMemo(() => {
    return (Array.isArray(data) ? data : []).map((row) => ({
      ...row,
      order_status: normalizeOrderStatus(String(row.order_status ?? '')),
    }))
  }, [data])

  const filteredData = useMemo(() => {
    let result = [...normalizedRows]
    const canonical: StatusTab[] = ['WELCOME', 'ORDER_CONFIRM', 'WAITING_OWNER', 'BOT_ACTIVE']
    if (canonical.includes(activeTab as StatusTab)) {
      result = result.filter((row) => row.order_status === activeTab)
    }
    if (dateFilterActive) {
      const filterStr = currentDate.toISOString().slice(0, 10)
      result = result.filter((row) => {
        if (!row.send_datetime) return false
        const rowDate = new Date(row.send_datetime as string).toISOString().slice(0, 10)
        return rowDate === filterStr
      })
    }
    if (searchText.trim()) {
      const q = searchText.toLowerCase()
      result = result.filter((row) =>
        Object.values(row ?? {}).some((value) =>
          String(value ?? '')
            .toLowerCase()
            .includes(q)
        )
      )
    }
    return result
  }, [normalizedRows, activeTab, dateFilterActive, currentDate, searchText])

  function formatDate(date: Date) {
    const weekdays = ['日', '一', '二', '三', '四', '五', '六']
    return `${date.getMonth() + 1} 月 ${date.getDate()} 日 (${weekdays[date.getDay()]})`
  }

  function formatDateTime(datetime: string | null | undefined) {
    if (!datetime) return ''
    const date = new Date(datetime)
    const weekdays = ['日', '一', '二', '三', '四', '五', '六']
    const day = date.getDate().toString().padStart(2, '0')
    const month = (date.getMonth() + 1).toString().padStart(2, '0')
    const year = date.getFullYear().toString().slice(-2)
    const hours = date.getHours().toString().padStart(2, '0')
    const minutes = date.getMinutes().toString().padStart(2, '0')
    return `${year}/${month}/${day}（${weekdays[date.getDay()]}）${hours}:${minutes}`
  }

  function goToPreviousDay() {
    const nd = new Date(currentDate)
    nd.setDate(nd.getDate() - 1)
    setCurrentDate(nd)
    setDateFilterActive(true)
    setActiveTab('')
  }

  function goToNextDay() {
    const nd = new Date(currentDate)
    nd.setDate(nd.getDate() + 1)
    setCurrentDate(nd)
    setDateFilterActive(true)
    setActiveTab('')
  }

  function downloadCSV() {
    const rows = data.map((row) => [
      row.order_status,
      row.id,
      row.order_status,
      row.send_datetime,
      row.customer_name,
      row.customer_phone,
      row.item,
      row.quantity,
      row.note,
      row.shipment_method === 'store_pickup' ? '店取' : '外送',
      row.total_amount,
      row.pay_way,
      row.pay_status,
      row.id,
    ])

    const csvContent = [columnName, ...rows]
      .map((row) =>
        row.map((cell) => `"${String(cell ?? '').replace(/"/g, '""')}"`).join(',')
      )
      .join('\n')

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
    const link = document.createElement('a')
    link.href = URL.createObjectURL(blob)
    link.setAttribute('download', '訂單資料.csv')
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(link.href)
  }

  async function handleExportDocx(orderId: number | string) {
    try {
      const blob = await exportDocx(orderId)
      const url = window.URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      link.setAttribute('download', `order_${orderId}.docx`)
      document.body.appendChild(link)
      link.click()
      link.remove()
      window.URL.revokeObjectURL(url)
    } catch (error: unknown) {
      console.error('Error exporting docx:', error)
      alert(`匯出工單失敗: ${getErrorDetail(error)}`)
    }
  }

  async function handleCancelOrder(orderId: number | string) {
    if (!window.confirm('確定要刪除此訂單嗎？此操作無法復原。')) return
    try {
      await deleteOrder(orderId)
      alert('訂單已成功取消')
      await onOrderDeleted?.()
    } catch (error: unknown) {
      console.error('Error canceling order:', error)
      alert(`取消訂單時發生錯誤：${getErrorDetail(error)}`)
    }
  }

  function setTab(tab: StatusTab) {
    setActiveTab(tab)
    setDateFilterActive(false)
  }

  function onDateFilterClick() {
    setDateFilterActive(true)
    setActiveTab('')
  }

  function cellValue(column: string, row: OrderRecord): ReactNode {
    const key = columnMapping[column]
    if (column === '匯出工單') {
      return (
        <button
          type="button"
          className="work-order-btn"
          onClick={() => handleExportDocx(row.id)}
        >
          工單
        </button>
      )
    }
    if (column === '取消訂單') {
      return (
        <button type="button" className="cancel-order-btn" onClick={() => handleCancelOrder(row.id)}>
          刪除
        </button>
      )
    }
    const rawKey = key as keyof OrderRecord
    const value = row[rawKey]
    if (column === '取貨時間') {
      return formatDateTime(value as string)
    }
    if (column === '取貨方式') {
      return value === 'store_pickup' ? '店取' : '外送'
    }
    if (column === '狀態') {
      const st = String(value ?? '')
      return (
        <span className={`status-badge ${orderStatusBadgeClass(st)}`}>
          {getStatusDisplay(normalizeOrderStatus(st))}
        </span>
      )
    }
    return String(value ?? '')
  }

  return (
    <div className="order-section">
      <div className="order-title-row">
        <span className="order-table-title">訂單總覽</span>
      </div>
      <div className="order-filter-row">
        <div className="order-tabs">
          <button
            type="button"
            className={`tab${activeTab === 'WELCOME' ? ' active' : ''}`}
            onClick={() => setTab('WELCOME')}
          >
            歡迎
          </button>
          <button
            type="button"
            className={`tab${activeTab === 'ORDER_CONFIRM' ? ' active' : ''}`}
            onClick={() => setTab('ORDER_CONFIRM')}
          >
            等待備貨
          </button>
          <button
            type="button"
            className={`tab${activeTab === 'WAITING_OWNER' ? ' active' : ''}`}
            onClick={() => setTab('WAITING_OWNER')}
          >
            人工溝通
          </button>
          <button
            type="button"
            className={`tab${activeTab === 'BOT_ACTIVE' ? ' active' : ''}`}
            onClick={() => setTab('BOT_ACTIVE')}
          >
            自動回覆
          </button>
        </div>
        <div className="date-filter compact">
          <button type="button" className="date-nav-btn" onClick={goToPreviousDay}>
            <span className="arrow">&#60;</span>
          </button>
          <button
            type="button"
            className="current-date"
            onClick={onDateFilterClick}
            style={{
              cursor: 'pointer',
              fontWeight: dateFilterActive ? 'bold' : 'normal',
              color: dateFilterActive ? '#6168FC' : undefined,
              border: 'none',
              background: 'transparent',
              fontFamily: 'inherit',
            }}
          >
            {formatDate(currentDate)}
          </button>
          <button type="button" className="date-nav-btn" onClick={goToNextDay}>
            <span className="arrow">&#62;</span>
          </button>
        </div>
        <div className="search-group">
          <input
            type="text"
            className="search-input"
            placeholder="搜尋訂單（姓名、編號等）"
            value={searchText}
            onChange={(e) => setSearchText(e.target.value)}
          />
          <span className="search-icon">
            <i className="fas fa-search" />
          </span>
        </div>
        <button type="button" className="download-btn" onClick={downloadCSV}>
          <i className="fas fa-download" />
          <span>下載 CSV</span>
        </button>
      </div>
      <div className="table-container">
        <div className="table-wrapper-inner">
          <table className="table table-hover align-middle">
            <thead>
              <tr>
                {columnName.map((column) => (
                  <th key={column} style={{ width: columnWidths[column] }}>
                    {column}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {filteredData.map((row) => (
                <tr key={String(row.id)}>
                  {columnName.map((column) => (
                    <td key={column} style={{ width: columnWidths[column] }}>
                      {cellValue(column, row)}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        {filteredData.length === 0 ? (
          <div className="no-results">
            <i className="fas fa-search fa-2x mb-3" />
            <p>找不到符合條件的訂單</p>
          </div>
        ) : null}
      </div>
    </div>
  )
}

// frontend/src/components/OrderTable.vue
<script setup>
import { ref, computed } from 'vue'
import { exportDocx, deleteOrder } from '@/api/orders'

const props = defineProps({
  data: {
    type: Array,
    required: true
  },
  columnName: {
    type: Array,
    required: true
  }
})

const emit = defineEmits(['orderDeleted'])

// Add mapping between column names and data properties
const columnMapping = {
  '匯出工單': 'order_status',
  '訂單編號': 'id',
  '狀態': 'order_status',
  '取貨時間': 'send_datetime',
  '姓名': 'customer_name',
  '電話': 'customer_phone',
  '商品': 'item',
  '數量': 'quantity',
  '備註': 'note',
  '取貨方式': 'shipment_method',
  '金額': 'total_amount',
  '付款方式': 'pay_way',
  '付款狀態': 'pay_status',
  '取消訂單':'id'
}

const searchText = ref('')
const currentDate = ref(new Date())
const activeTab = ref('WELCOME')
const dateFilterActive = ref(false)

const formatDate = (date) => {
  const weekdays = ['日', '一', '二', '三', '四', '五', '六']
  return `${date.getMonth() + 1} 月 ${date.getDate()} 日 (${weekdays[date.getDay()]})`
}

const goToPreviousDay = () => {
  const newDate = new Date(currentDate.value)
  newDate.setDate(newDate.getDate() - 1)
  currentDate.value = newDate
  dateFilterActive.value = true
  activeTab.value = ''
}

const goToNextDay = () => {
  const newDate = new Date(currentDate.value)
  newDate.setDate(newDate.getDate() + 1)
  currentDate.value = newDate
  dateFilterActive.value = true
  activeTab.value = ''
}

const formatDateTime = (datetime) => {
  if (!datetime) return ''
  const date = new Date(datetime)
  const weekdays = ['日', '一', '二', '三', '四', '五', '六']
  const day = date.getDate().toString().padStart(2, '0')
  const month = (date.getMonth() + 1).toString().padStart(2, '0')
  const year = date.getFullYear().toString().slice(-2)
  const hours = date.getHours().toString().padStart(2, '0')
  const minutes = date.getMinutes().toString().padStart(2, '0')
  return `${year}/${month}/${day}（${weekdays[date.getDay()]}）${hours}:${minutes}`
}

// 狀態顏色對應
function statusColor(status) {
  switch (status) {
    case 'MANUAL': return 'badge-manual'
    case 'CONFIRMED': return 'badge-prepare'
    case 'FINISH': return 'badge-finish'
    default: return 'badge-manual'
  }
}

// 狀態文字對應
function statusText(status) {
  switch (status) {
    case 'WELCOME': return '歡迎'
    case 'ORDER_CONFIRM': return '等待備貨'
    case 'WAITING_OWNER': return '人工溝通'
    case 'BOT_ACTIVE': return '自動回覆'
    default: return status
  }
}

// 狀態 mapping，確保只會有四個狀態
function normalizeStatus(status) {
  switch (status) {
    case 'WELCOME':
    case 'ORDER_CONFIRM':
    case 'WAITING_OWNER':
    case 'BOT_ACTIVE':
      return status
      
    case 'MANUAL':
      return 'WAITING_OWNER'
    case 'CONFIRMED':
      return 'ORDER_CONFIRM'
    case 'AUTO':
      return 'BOT_ACTIVE'
    // 其他未對應的狀態預設為 WAITING_OWNER
    default:
      return 'WAITING_OWNER'
  }
}

// 只根據四個狀態 tab 並做狀態正規化
const filteredData = computed(() => {
  if (!Array.isArray(props.data)) return []
  let result = props.data.map(row => ({
    ...row,
    order_status: normalizeStatus(row.order_status)
  }))
  // 狀態 tab 篩選
  if (['WELCOME', 'ORDER_CONFIRM', 'WAITING_OWNER', 'BOT_ACTIVE'].includes(activeTab.value)) {
    result = result.filter(row => row.order_status === activeTab.value)
  }
  // 日期篩選
  if (dateFilterActive.value) {
    const filterStr = currentDate.value.toISOString().slice(0, 10)
    result = result.filter(row => {
      if (!row.send_datetime) return false
      const rowDate = new Date(row.send_datetime).toISOString().slice(0, 10)
      return rowDate === filterStr
    })
  }
  // 搜尋文字
  if (searchText.value) {
    result = result.filter(row =>
      Object.values(row || {}).some(value =>
        String(value).toLowerCase().includes(searchText.value.toLowerCase())
      )
    )
  }
  return result
})

// 匯出成 CSV 檔案
function downloadCSV() {
  const headers = props.columnName
  const rows = props.data.map(row => [
    row.order_status,
    row.id,
    row.order_status,
    row.send_datetime,
    // new Date(row.send_datetime).toLocaleString(),
    row.customer_name,
    row.customer_phone,
    row.item,
    row.quantity,
    row.note,
    row.shipment_method === 'store_pickup' ? '店取' : '外送',
    row.total_amount,
    row.pay_way,
    row.pay_status,
    row.id
  ])

  const csvContent = [headers, ...rows]
    .map(row => row.map(cell => `"${String(cell).replace(/"/g, '""')}"`).join(','))
    .join('\n')

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
  const link = document.createElement('a')
  link.href = URL.createObjectURL(blob)
  link.setAttribute('download', '訂單資料.csv')
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
}

const handleExportDocx = async (orderId) => {
  try {
    const blob = await exportDocx(orderId)
    // Create a download link
    const url = window.URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.setAttribute('download', `order_${orderId}.docx`)
    document.body.appendChild(link)
    link.click()
    // Clean up
    link.remove()
    window.URL.revokeObjectURL(url)
  } catch (error) {
    console.error('Error exporting docx:', error)
    alert('匯出工單失敗: ' + error.message)
  }
}

const handleCancelOrder = async (orderId) => {
  try {
    // Add confirmation dialog
    if (!confirm('確定要刪除此訂單嗎？此操作無法復原。')) {
      return
    }

    await deleteOrder(orderId)
    // Show success message
    alert('訂單已成功取消')
    // Emit event to refresh the order list
    emit('orderDeleted', orderId)
  } catch (error) {
    console.error('Error canceling order:', error)
    alert('取消訂單時發生錯誤：' + (error.response?.data?.detail || error.message))
  }
}

const columnWidths = {
  '訂單編號': '136px',
  '狀態': '120px',
  '取貨時間': '200px',
  '姓名': '96px',
  '電話': '112px',
  '商品': '96px',
  '數量': '96px',
  '備註': '128px',
  '取貨方式': '128px',
  '金額': '96px',
  '付款方式': '128px',
  '付款狀態': '112px',
  '取消訂單':'96px' 
}

// 點擊日期filter按鈕時觸發
function onDateFilterClick() {
  dateFilterActive.value = true
  activeTab.value = '' // 取消tab篩選
}

// 點擊訂單總覽時觸發
function onOrderTitleClick() {
  dateFilterActive.value = false
  activeTab.value = 'all'
}
</script>

<template>
  <div class="section" id="orders">
    <div class="order-title-row">
      <span class="order-title">訂單總覽</span>
    </div>
    <div class="order-filter-row">
      <div class="order-tabs">
        <button 
          class="tab" 
          :class="{ active: activeTab === 'WELCOME' }"
          @click="activeTab = 'WELCOME'; dateFilterActive = false;"
        >歡迎</button>
        <button 
          class="tab" 
          :class="{ active: activeTab === 'ORDER_CONFIRM' }"
          @click="activeTab = 'ORDER_CONFIRM'; dateFilterActive = false;"
        >等待備貨</button>
        <button 
          class="tab" 
          :class="{ active: activeTab === 'WAITING_OWNER' }"
          @click="activeTab = 'WAITING_OWNER'; dateFilterActive = false;"
        >人工溝通</button>
        <button 
          class="tab" 
          :class="{ active: activeTab === 'BOT_ACTIVE' }"
          @click="activeTab = 'BOT_ACTIVE'; dateFilterActive = false;"
        >自動回覆</button>
      </div>
      <div class="date-filter">
        <button class="date-nav-btn" @click="goToPreviousDay">
          <span class="arrow">&#60;</span>
        </button>
        <div class="current-date" @click="onDateFilterClick" :style="{cursor:'pointer', fontWeight: dateFilterActive ? 'bold' : 'normal', color: dateFilterActive ? '#6168FC' : ''}">{{ formatDate(currentDate) }}</div>
        <button class="date-nav-btn" @click="goToNextDay">
          <span class="arrow">&#62;</span>
        </button>
      </div>
      <div class="search-group">
        <input
          type="text"
          v-model="searchText"
          class="search-input"
          placeholder="搜尋訂單（姓名、編號等）"
        />
        <span class="search-icon"><i class="fas fa-search"></i></span>
      </div>
      <button @click="downloadCSV" class="download-btn">
        <i class="fas fa-download"></i>
        <span>下載 CSV</span>
      </button>
    </div>
    <div class="table-container">
      <div class="table-wrapper">
        <table class="table table-hover align-middle">
          <thead>
            <tr>
              <th v-for="column in columnName" :key="column" :style="{ width: columnWidths[column] }">
                {{ column }}
              </th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="row in filteredData" :key="row.id">
              <td v-for="column in columnName" :key="column" :style="{ width: columnWidths[column] }">
                <template v-if="column === '匯出工單'">
                  <button class="work-order-btn" @click="handleExportDocx(row.id)">工單</button>
                </template>
                <template v-else-if="column === '取消訂單'">
                  <button class="cancel-order-btn" @click="handleCancelOrder(row.id)">刪除</button>
                </template>
                <template v-else-if="column === '取貨時間'">
                  {{ formatDateTime(row[columnMapping[column]]) }}
                </template>
                <template v-else-if="column === '取貨方式'">
                  {{ row[columnMapping[column]] === 'store_pickup' ? '店取' : '外送' }}
                </template>
                <template v-else-if="column === '狀態'">
                  <span :class="['status-badge', statusColor(row[columnMapping[column]])]">
                    {{ statusText(row[columnMapping[column]]) }}
                  </span>
                </template>
                <template v-else>
                  {{ row[columnMapping[column]] }}
                </template>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <div v-if="filteredData.length === 0" class="no-results">
        <i class="fas fa-search fa-2x mb-3"></i>
        <p>找不到符合條件的訂單</p>
      </div>
    </div>
  </div>
</template>

<style scoped>
.section {
  background: #fff;
  border-radius: 8px;
  padding-top: 24px;
  padding-bottom: 24px;
  padding-left: 32px;
  padding-right: 32px;
  margin-top: 24px;
  margin-bottom: 32px;
  border-bottom: 1.5px solid #e9e9e9;
}
.order-title-row {
  width: 100%;
  margin-bottom: 8px;
}
.order-title {
  color: #4F51FF;
  font-size: 22px;
  font-weight: 700;
  letter-spacing: 1px;
  white-space: nowrap;
}
.order-filter-row {
  display: flex;
  align-items: center;
  gap: 16px;
  flex-wrap: nowrap;
  width: 440px;
    margin-bottom: 16px;
}
.order-tabs {
  display: inline-flex;
  gap: 4px;
  padding: 6px 12px;
  background: #F7F7F7;
  border-radius: 36px;
  height: 40px;
  align-items: center;
  flex-shrink: 0;
  overflow-x: auto;
}
.tab {
  display: flex;
  align-items: center;
  padding: 11px 24px;
  height: 28px;
  border-radius: 36px;
  border: none;
  background: transparent;
  font-family: 'Noto Sans TC', sans-serif;
  font-weight: 700;
  font-size: 14px;
  line-height: 112.5%;
  color: rgba(0, 0, 0, 0.6);
  cursor: pointer;
  transition: all 0.2s;
  white-space: nowrap;
  flex-shrink: 0;
}
.tab.active {
  background: #C5C7FF;
  border-radius: 36px;
}
.date-filter {
  height: 28px;
  display: flex;
  align-items: center;
  padding: 11px 24px;
  gap: 8px;
  border-radius: 36px;
  background: #F7F7F7;
}
.search-group {
  position: relative;
  width: 360px;
  min-width: 360px;
  height: 46px;
  background: #D8EAFF;
  border-radius: 36px;
  display: flex;
  align-items: center;
  padding: 11px 24px;
}
.search-input {
  width: 100%;
  border: none;
  background: transparent;
  font-family: 'Noto Sans TC', sans-serif;
  font-weight: 400;
  font-size: 16px;
  line-height: 140%;
  color: rgba(0, 0, 0, 0.38);
  padding: 0;
}
.search-input::placeholder {
  color: rgba(0, 0, 0, 0.38);
}
.search-icon {
  position: absolute;
  right: 24px;
  top: 50%;
  transform: translateY(-50%);
  width: 24px;
  height: 24px;
  color: rgba(0, 0, 0, 0.38);
}
.download-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 12px 12px;
  width: 113px;
  height: 46px;
  background: #77B5FF;
  box-shadow: 2px 2px 2px rgba(0, 0, 0, 0.25);
  border-radius: 12px;
  border: none;
  cursor: pointer;
  transition: all 0.2s;
  gap: 8px;
  white-space: nowrap;
}
.download-btn i {
  color: #FFFFFF;
  font-size: 20px;
  flex-shrink: 0;
  display: flex;
  align-items: center;
}
.download-btn span {
  font-family: 'Noto Sans TC', sans-serif;
  font-style: normal;
  font-weight: 700;
  font-size: 16px;
  line-height: 112.5%;
  color: #FFFFFF;
  white-space: nowrap;
  flex: none;
  order: 1;
  flex-grow: 0;
  width: 66px;
  height: 18px;
  display: flex;
  align-items: center;
}
.table-container {
  margin-top: 0;
  width: 100%;
  overflow: hidden;
}

.table-wrapper {
  width: 100%;
  overflow-x: auto;
  padding: 0 8px;
}

table {
  border-collapse: separate;
  border-spacing: 0 8px;
  width: max-content;
  min-width: 100%;
}

thead {
  position: sticky;
  top: 0;
  z-index: 1;
}

th {
  font-family: 'Noto Sans TC', sans-serif;
  font-weight: bold;
  font-size: 16px;
  line-height: 140%;
  color: rgba(0, 0, 0, 0.87);
  padding: 12px 20px;
  text-align: left;
  background-color: #F7F7F7;
  white-space: nowrap;
  position: relative;
  border: 0.5px solid rgba(175, 175, 175, 0.6);
}

th:first-child {
  border-top-left-radius: 12px;
  border-bottom-left-radius: 12px;
  border-right: none;
}

th:last-child {
  border-top-right-radius: 12px;
  border-bottom-right-radius: 12px;
  border-left: none;
}

th:not(:first-child):not(:last-child) {
  border-right: none;
  border-left: none;
}

td {
  padding: 12px 20px;
  text-align: left;
  font-family: 'Noto Sans TC', sans-serif;
  font-weight: bold;
  font-size: 16px;
  line-height: 140%;
  color: rgba(0, 0, 0, 0.6);
  vertical-align: middle;
  white-space: normal;
  word-wrap: break-word;
  max-width: v-bind('columnWidths[column]');
  background: #fff;
  border: 0.5px solid rgba(175, 175, 175, 0.6);
}

tr {
  background: #fff;
  border-radius: 12px;
}

td:first-child {
  border-top-left-radius: 12px;
  border-bottom-left-radius: 12px;
  border-right: none;
}

td:last-child {
  border-top-right-radius: 12px;
  border-bottom-right-radius: 12px;
  border-left: none;
}

td:not(:first-child):not(:last-child) {
  border-right: none;
  border-left: none;
}

tr:hover td {
  background-color: #f0f6ff;
}

.status-badge {
  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: center;
  padding: 6px 16px;
  gap: 10px;
  height: 28px;
  border-radius: 8px;
  font-family: 'Noto Sans TC', sans-serif;
  font-style: normal;
  font-weight: 700;
  font-size: 14px;
  line-height: 112.5%;
  text-align: center;
  white-space: nowrap;
}

.badge-welcome {
  background: #FFCEE7;
  color: #FF349A;
}

.badge-prepare {
  background: #C5C7FF;
  color: #6168FC;
}

.badge-wait {
  background: #EBCDCC;
  color: #81386A;
}

.badge-auto {
  background: #D8EAFF;
  color: #6168FC;
}

.money {
  color: #4F8CFF;
  font-weight: bold;
  font-size: 16px;
}
.text-danger {
  color: #FF6F91;
  font-weight: bold;
}
.no-results {
  text-align: center;
  padding: 40px;
  color: #aaa;
}
.date-filter {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 0 16px;
  height: 40px;
  background: #F7F7F7;
  border-radius: 36px;
  margin: 0 8px;
}

.date-nav-btn {
  background: #D9D9D9;
  color: white;
  border: none;
  border-radius: 50%;
  width: 28px;
  height: 28px;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  transition: background-color 0.2s;
  padding: 0;
}

.date-nav-btn:hover {
  background: #C5C7FF;
}

.arrow {
  font-size: 14px;
  font-weight: bold;
  line-height: 1;
}

.current-date {
  font-family: 'Noto Sans TC', sans-serif;
  font-weight: 700;
  font-size: 14px;
  line-height: 112.5%;
  color: rgba(0, 0, 0, 0.4);
  min-width: 80px;
  text-align: center;
  white-space: nowrap;
}

.work-order-btn {
  /* Auto layout */
  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: center;
  padding: 6px 16px;
  gap: 10px;

  width: 60px;
  max-width: 92px;
  height: 28px;

  /* Secondary/Default */
  background: #77B5FF;
  border-radius: 8px;

  /* Inside auto layout */
  flex: none;
  order: 0;
  flex-grow: 0;

  /* Text styling */
  font-family: 'Noto Sans TC', sans-serif;
  font-style: normal;
  font-weight: 700;
  font-size: 14px;
  line-height: 112.5%;
  color: #FFFFFF;
  text-align: center;

  /* Button reset */
  border: none;
  cursor: pointer;
  transition: opacity 0.2s;
}

.work-order-btn:hover {
  opacity: 0.8;
}

.cancel-order-btn {
  /* Auto layout */
  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: center;
  padding: 6px 16px;
  gap: 10px;

  width: 60px;
  max-width: 92px;
  height: 28px;

  /* Alert/Default */
  background: #AE1914;
  border-radius: 8px;

  /* Inside auto layout */
  flex: none;
  order: 0;
  flex-grow: 0;

  /* Text styling */
  font-family: 'Noto Sans TC', sans-serif;
  font-style: normal;
  font-weight: 700;
  font-size: 14px;
  line-height: 112.5%;
  color: #EBCDCC;
  text-align: center;

  /* Button reset */
  border: none;
  cursor: pointer;
  transition: opacity 0.2s;
}

.cancel-order-btn:hover {
  opacity: 0.8;
}
</style>
