// frontend/src/components/MessageItem.vue
<template>
  <!-- 日期區塊 -->
  <div v-if="message.isDate" class="date-block">
    <span class="date-text">{{ message.text }}</span>
  </div>

  <!-- 對方訊息（message customer）；頭像欄固定寬，同分鐘連續訊息才不會跑版 -->
  <div v-else-if="message.direction === 'INCOMING'" class="message-customer">
    <div class="avatar-slot">
      <img
        v-if="message.isFirstInMinute"
        class="pic"
        :src="message.avatar || ''"
        :alt="message.sender"
        @error="onImgError"
      />
    </div>
    <div class="message-bubble">
      <div class="sender">
        <span class="message-text">{{ message.text }}</span>
      </div>
      <span class="time">{{ formatTime(message.timestamp) }}</span>
    </div>
  </div>

  <!-- 自己訊息（message myself） -->
  <div v-else class="message-myself">
    <div class="message-bubble">
      <div class="sender myself">
        <span class="message-text">{{ message.text }}</span>
      </div>
      <span class="time myself">{{ formatTime(message.timestamp) }}</span>
    </div>
  </div>
</template>

<script setup>
import { format } from 'date-fns'
import { computed } from 'vue'

const props = defineProps({
  message: Object
})

const isOutgoing = computed(() => {
  return props.message.direction === 'OUTGOING_BY_STAFF' || 
         props.message.direction === 'OUTGOING_BY_BOT'
})

function formatTime(timestamp) {
  return format(new Date(timestamp), 'HH:mm')
}
function onImgError(event) {
  event.target.src = '' // 讓 src 變空，觸發預設灰色圈圈樣式
}
</script>

<style scoped>
/* 日期區塊 */
.date-block {
  width: 87px;
  height: 24px;
  margin: 0 auto 12px;
  border-radius: 8px;
  padding: 2px 8px;
  background: #C5C7FF;
  display: flex;
  align-items: center;
  justify-content: center;
}
.date-text {
  font-family: 'Noto Sans TC';
  font-weight: 400;
  font-size: 14px;
  line-height: 140%;
  color: #fff;
  text-align: center;
}

.message-bubble {
  display: flex;
  align-items: flex-end;
  gap: 2px;
  min-height: 40px;
  max-width: 360px;
}

/* 對方訊息 */
.message-customer {
  display: flex;
  align-items: flex-end;
  gap: 12px;
  min-height: 40px;
  margin-left: 0;
  margin-bottom: 12px;
}
.avatar-slot {
  width: 32px;
  flex-shrink: 0;
  display: flex;
  align-items: flex-end;
  justify-content: center;
  align-self: flex-end;
  margin-bottom: 4px;
}
.pic {
  width: 32px;
  height: 32px;
  border-radius: 50%;
  object-fit: cover;
  background: #D9D9D9;
  /* 沒有 src 時顯示灰色 */
  display: block;
}
.pic[src=""] {
  background: #D9D9D9;
}

.sender {
  min-height: 40px;
  max-width: 360px;
  border-radius: 24px;
  padding: 9px 16px;
  background: #D9D9D9;
  word-break: break-word;
  
  display: inline-block;
  align-items: center;
}
.message-text {
  font-family: 'Noto Sans TC';
  font-weight: 400;
  font-size: 16px;
  line-height: 140%;
  color: #000000DE;
}
.time {
  width: 50px;
  height: 17px;
  font-family: 'Noto Sans TC';
  font-weight: 400;
  font-size: 12px;
  line-height: 140%;
  color: #00000061;
  border-radius: 8px;
  display: flex;
  align-items: center;
  justify-content: center;
  margin-left: 0px;
}

/* 自己訊息 */
.message-myself {
  display: flex;
  justify-content: flex-end;
  min-height: 40px;
  margin-right: 0;
  margin-bottom: 12px;
}
.message-myself .message-bubble {
  flex-direction: row-reverse;
  gap: 2px;
}
.sender.myself {
  background: #77B5FF;
  color: #fff;
}
.message-myself .message-text {
  color: #fff;
}
.time.myself {
  width: 44px;
  color: #00000061;
  border-radius: 8px;
  display: flex;
  align-items: center;
  justify-content: center;
  margin-right: 4px;
  margin-left: 0;
  padding: 0 6px;
}
</style>

// frontend/src/components/messages/MessageItem.tsx
import type { SyntheticEvent } from 'react'
import { format } from 'date-fns'
import type { ChatMessageUi } from '@/types/models'
import './MessageItem.css'

type MessageItemProps = {
  message:
    | ChatMessageUi
    | { isDate?: true; text: string; id: string | number }
    | (ChatMessageUi & { isFirstInMinute?: boolean })
}

export default function MessageItem({ message }: MessageItemProps) {
  if ('isDate' in message && message.isDate) {
    return (
      <div className="date-block">
        <span className="date-text">{message.text}</span>
      </div>
    )
  }

  const msg = message as ChatMessageUi & { isFirstInMinute?: boolean }

  function formatTime(timestamp: Date | string) {
    return format(new Date(timestamp), 'HH:mm')
  }

  function onImgError(event: SyntheticEvent<HTMLImageElement>) {
    event.currentTarget.src = ''
  }

  if (msg.direction === 'INCOMING') {
    return (
      <div className="message-customer">
        <div className="avatar-slot">
          {msg.isFirstInMinute ? (
            <img className="pic" src={msg.avatar || ''} alt={msg.sender} onError={onImgError} />
          ) : null}
        </div>
        <div className="message-bubble">
          <div className="sender">
            <span className="message-text">{msg.text}</span>
          </div>
          <span className="time">{formatTime(msg.timestamp)}</span>
        </div>
      </div>
    )
  }

  return (
    <div className="message-myself">
      <div className="message-bubble">
        <div className="sender myself">
          <span className="message-text">{msg.text}</span>
        </div>
        <span className="time myself">{formatTime(msg.timestamp)}</span>
      </div>
    </div>
  )
}
